from . import base
from . import auth
from . import autor
from . import categoria
from . import cliente
from . import compra
from . import editorial
from . import image
from . import libro
from . import tarjeta